print_int (int_of_float (floor 12.0));
print_char 10;
print_int (int_of_float (floor 12.1));
print_char 10;
print_int (int_of_float (floor 12.3));
print_char 10;
print_int (int_of_float (floor 12.5));
print_char 10;
print_int (int_of_float (floor 12.7));
print_char 10;
print_int (int_of_float (floor 12.9));
print_char 10;
print_int (int_of_float (fabs (floor -12.0)));
print_char 10;
print_int (int_of_float (fabs (floor -12.1)));
print_char 10;
print_int (int_of_float (fabs (floor -12.3)));
print_char 10;
print_int (int_of_float (fabs (floor -12.5)));
print_char 10;
print_int (int_of_float (fabs (floor -12.7)));
print_char 10;
print_int (int_of_float (fabs (floor -12.9)));
print_char 10;
print_int (int_of_float (fabs (floor 0.0)));
print_char 10;
print_int (int_of_float (fabs (floor -0.0)));
print_char 10
